const lguTypes = {
    ADD_NEW_LGU_START: 'ADD_NEW_LGU_STAR',
    FETCH_LGU_START: 'FETCH_LGU_START',
    SET_LGU: 'SET_LGU',
    DELETE_LGU_START: 'DELETE_LGU_START',
    FETCH_LGUT_START: 'FETCH_LGUT_START'
};

export default lguTypes;